apiVersion: apps/v1
kind: Deployment
metadata:
  name: subchart-d
  annotations:
    rev: {{ .Values.global.rev | quote }}
spec:
  replicas: 1
  selector:
    matchLabels: {app: subchart-d}
  template:
    metadata:
      labels: {app: subchart-d}
      annotations:
        rev: {{ .Values.global.rev | quote }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: web
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet: {path: /, port: 80}
            initialDelaySeconds: {{ .Values.readyDelay }}
            periodSeconds: 1
