apiVersion: apps/v1
kind: Deployment
metadata:
  name: parent
spec:
  replicas: 1
  selector:
    matchLabels: {app: parent}
  template:
    metadata:
      labels: {app: parent}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: web
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet: {path: /, port: 80}
            initialDelaySeconds: {{ .Values.readyDelay }}
            periodSeconds: 1
