apiVersion: v3
name: child-b
description: child level depending on grandchild
version: 0.1.0
annotations:
  helm.sh/depends-on/subcharts: '["grandchild-a"]'
dependencies:
  - name: grandchild-a
    version: 0.1.0
    repository: file://charts/grandchild-a
