apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependent
spec:
  replicas: 1
  selector:
    matchLabels: {app: dependent}
  template:
    metadata:
      labels: {app: dependent}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: web
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
